vaadin.launch-browser=true
spring.application.name=chatdocs
spring.config.import=optional:file:.env[.properties]

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}

