vaadin.launch-browser=true
spring.application.name=chatdocs
spring.config.import=optional:file:.env[.properties]
spring.profiles.default=dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}

